(lang dune 3.20)

(name zoo)

(generate_opam_files true)

(source
 (github username/reponame))

(authors "Author Name <author@example.com>")

(maintainers "Maintainer Name <maintainer@example.com>")

(license LICENSE)

(documentation https://url/to/documentation)

(package
 (name zoo)
 (synopsis "A short synopsis")
 (description "A longer description")
 (depends
   core
   core_unix
   (dune (and (>= 3.20) (< 3.21)))
   (ocaml (and (>= 5.3) (< 5.4)))
   logs
   utop)
 (tags
  ("add topics" "to describe" your project)))

; See the complete stanza docs at https://dune.readthedocs.io/en/stable/reference/dune-project/index.html
